name: build

on:
  push:
  schedule:
    - cron: 0 12 1 * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: npm ci
    - run: npm run lint
    - run: npm run build

  test-latest:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup just
      uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Test
      run: |
        [ "$(just --justfile tests/Justfile)" = "Test..." ]
      shell: bash

  test-version:
    needs: test-latest
    strategy:
      matrix:  # https://github.com/casey/just/releases
        just-version: [0.5.11, 0.6.1, 0.7.3, 0.8.7, 0.9.9, 0.10.7, 0.11.2, 1.5.0, 1.23.0]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run self
      uses: ./
      with:
        just-version: ${{ matrix.just-version }}
    - name: Check version
      run: just --version | grep -E "^just v?${{ matrix.just-version }}$"
    - name: Test
      run: |
        [ "$(just --justfile tests/Justfile)" = "Test..." ]
